export default {
  CARD: 'card',

  PENDING: '_PENDING',
  FULFILLED: '_FULFILLED',
  REJECTED: '_REJECTED',

  FETCH_CARDS: 'FETCH_CARDS',

  TOGGLE_CARD_DETAILS: 'TOGGLE_CARD_DETAILS',

  CREATE_CARD: 'CREATE_CARD',

  UPDATE_CARD: 'UPDATE_CARD',

  UPDATE_CARD_STATUS: 'UPDATE_CARD_STATUS',

  UPDATE_CARD_POSITION: 'UPDATE_CARD_POSITION',

  PERSIST_CARD_DRAG: 'PERSIST_CARD_DRAG',

  CREATE_DRAFT: 'CREATE_DRAFT',
  
  UPDATE_DRAFT: 'UPDATE_DRAFT',

  CREATE_TASK: 'CREATE_TASK',

  DELETE_TASK: 'DELETE_TASK',

  TOGGLE_TASK: 'TOGGLE_TASK',

};
